// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/productos": {
            "get": {
                "description": "Obtener todos los productos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "productos"
                ],
                "summary": "Obtener todos los productos",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Token de autorización",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Respuesta"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Crear un nuevo producto",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "productos"
                ],
                "summary": "Crear un nuevo producto",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \"",
                        "description": "Token de autorización",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Datos del producto a crear",
                        "name": "producto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Producto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.Respuesta"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.Respuesta"
                        }
                    }
                }
            }
        },
        "/v1/productos/{id}": {
            "get": {
                "description": "Obtener un producto por ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "productos"
                ],
                "summary": "Obtener un producto por ID",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \"",
                        "description": "Token de autorización",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID del producto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Respuesta"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.Respuesta"
                        }
                    }
                }
            },
            "put": {
                "description": "Actualizar un producto por ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "productos"
                ],
                "summary": "Actualizar un producto",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \"",
                        "description": "Token de autorización",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID del producto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del producto a actualizar",
                        "name": "producto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Producto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Respuesta"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.Respuesta"
                        }
                    }
                }
            },
            "delete": {
                "description": "Eliminar un producto por ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "productos"
                ],
                "summary": "Eliminar un producto",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \"",
                        "description": "Token de autorización",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID del producto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Respuesta"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.Respuesta"
                        }
                    }
                }
            },
            "patch": {
                "description": "Actualizar parcialmente un producto por ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "productos"
                ],
                "summary": "Actualizar parcialmente un producto",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \"",
                        "description": "Token de autorización",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID del producto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del producto a actualizar",
                        "name": "updates",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Respuesta"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.Respuesta"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Producto": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "descripcion": {
                    "type": "string"
                },
                "foto": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "otras_propiedades": {
                    "type": "object",
                    "additionalProperties": true
                },
                "precio": {
                    "type": "number"
                },
                "talla": {
                    "type": "string"
                }
            }
        },
        "main.Respuesta": {
            "type": "object",
            "properties": {
                "datos": {},
                "error": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "https://swagger-demo-shop-t-shirt.onrender.com/",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "APIs Swagger-Shop-t-Shirt",
	Description:      "API para gestionar productos (Shop-t-shirt)\n@dontesterlabs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
