name: Build and Deploy Swagger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Init go.mod
        run: go mod init swagger-demo-Shop-t-shirt
  
      - name: Update dependencies
        run: go mod tidy

      - name: Install swag
        run: |
          GO111MODULE=off go get -u github.com/swaggo/swag/cmd/swag
          export GO111MODULE=on
          export PATH=$PATH:$(go env GOPATH)/bin        

      - name: Generate Swagger docs
        run: swag init

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build Go binary
        run: go build -o myapp

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
