name: Build and Deploy Swagger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Go Version
        run: go version

      - name: Init go.mod
        run: go mod init swagger-demo-Shop-t-shirt
  
      - name: Update dependencies
        run: |
          go clean -modcache
          go mod tidy

      - name: Install swag
        run: |
          go get -u github.com/swaggo/swag/cmd/swag
          go install github.com/swaggo/swag/cmd/swag

      - name: Generate Swagger docs
        run: |
          swag init
          cd docs && ls -la     
